# This file is managed by Qt Creator, do not edit!

set("CMAKE_COLOR_DIAGNOSTICS" "ON" CACHE "BOOL" "" FORCE)
set("CMAKE_CXX_COMPILER" "C:/Program Files/Microsoft Visual Studio/18/Community/VC/Tools/MSVC/14.50.35717/bin/HostX64/x64/cl.exe" CACHE "FILEPATH" "" FORCE)
set("CMAKE_C_COMPILER" "C:/Program Files/Microsoft Visual Studio/18/Community/VC/Tools/MSVC/14.50.35717/bin/HostX64/x64/cl.exe" CACHE "FILEPATH" "" FORCE)
set("CMAKE_GENERATOR" "Ninja Multi-Config" CACHE "STRING" "" FORCE)
set("CMAKE_INSTALL_PREFIX" "C:/Users/Usuario/Desktop/Proyectos/Launcher/install" CACHE "PATH" "" FORCE)
set("CMAKE_MAKE_PROGRAM" "C:/Qt/Tools/Ninja/ninja.exe" CACHE "STRING" "" FORCE)
set("CMAKE_PREFIX_PATH" "" CACHE "PATH" "" FORCE)
set("CMAKE_PROJECT_INCLUDE_BEFORE" "C:/Users/Usuario/Desktop/Proyectos/Launcher/.qtcreator/cmake-helper/qtcreator-project.cmake" CACHE "FILEPATH" "" FORCE)
set("CMAKE_TOOLCHAIN_FILE" "C:/Users/Usuario/Desktop/Proyectos/Launcher/vcpkg/scripts/buildsystems/vcpkg.cmake" CACHE "STRING" "" FORCE)
set("ENABLE_LTO" "ON" CACHE "BOOL" "" FORCE)
set("Launcher_BUILD_ARTIFACT" "" CACHE "STRING" "" FORCE)
set("Launcher_BUILD_PLATFORM" "" CACHE "STRING" "" FORCE)
set("Launcher_ENABLE_JAVA_DOWNLOADER" "ON" CACHE "BOOL" "" FORCE)
set("QT_CREATOR_ENABLE_MAINTENANCE_TOOL_PROVIDER" "ON" CACHE "BOOL" "" FORCE)
set("QT_CREATOR_ENABLE_PACKAGE_MANAGER_SETUP" "ON" CACHE "BOOL" "" FORCE)
set("QT_QMAKE_EXECUTABLE" "" CACHE "FILEPATH" "" FORCE)